import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

function layout({children}:any) {
  return (
    <div>
        {children}
    </div>
  )
}

export default layout